### PR TITLE
Get grbl-sim working with current edge/master.

### PR DESCRIPTION
**Pull request by alpharesearch**
Here are all the things I had to do to get the simulator working.

### CODE REVIEW

**Comment by EliteEng** [comment]
@alpharesearch I am wondering if you could help me to get this running, I am having a few problems getting it to compile in ubuntu.

grbl compiles and works perfectly, then I do a make clean from the grbl folder to clean it up.
when I add your repo files to a sim folder and try to compile I get a lot of errors like default.h is not getting included, are you getting these errors too?

```cc -Wall -g -DF_CPU=16000000 -include config.h -I. -DPLAT_LINUX  -c ../settings.c -o ../settings.o
../settings.c: In function ‘settings_restore_global_settings’:
../settings.c:71:33: error: ‘DEFAULT_STEP_PULSE_MICROSECONDS’ undeclared (first use in this function)
   settings.pulse_microseconds = DEFAULT_STEP_PULSE_MICROSECONDS;
                                 ^
../settings.c:71:33: note: each undeclared identifier is reported only once for each function it appears in
../settings.c:72:37: error: ‘DEFAULT_STEPPER_IDLE_LOCK_TIME’ undeclared (first use in this function)
   settings.stepper_idle_lock_time = DEFAULT_STEPPER_IDLE_LOCK_TIME;```

github has moved the arrows in the formatting but it is complaining about all the defines from default.h, do you have any ideas?

**Comment by abetusk** [comment]
I think the underlying issue is that somehow an include file with the `DEFAULTS_GENERIC` and `CPU_MAP_ATMEGA328P_TRADITIONAL` defines (or their equivalent) doesn't get included before they're used in other include files.

I get a bunch of warnings (about redefining defines) but this compiles for me using alpharesearch's grbl repo and grbl-sim:
```git
@@ -20,9 +20,10 @@ PLATFORM   = LINUX
 OBJECTS    = main.o simulator.o serial.o ../main.o ../protocol.o ../planner.o ../settings.o ../print.o ../nuts_bolts.o eeprom.o ../ser
 CLOCK      = 16000000
 EXE_NAME   = grbl_sim.exe
-COMPILE    = $(CC) -Wall -g -DF_CPU=$(CLOCK) -include config.h -I. -DPLAT_$(PLATFORM)
+COMPILE    = $(CC) -Wall -g -DF_CPU=$(CLOCK) -include config.h -I. -DPLAT_$(PLATFORM) -DDEFAULTS_GENERIC -DCPU_MAP_ATMEGA328P_TRADITIONAL
 LINUX_LIBRARIES = -lrt -pthread
 WINDOWS_LIBRARIES = 
```

That is, add the `-DDEFAULTS_GENERIC -DCPU_MAP_ATMEGA328P_TRADITIONAL` define directives to be passed in to gcc.

I'm sure there's a better solution fixing the underlying problem of telling gcc to include the proper files, either in order or at all, but I'm having trouble getting it to work.

**Comment by alpharesearch** [comment]
The workaround I'm using is to go to grbl config.h and comment out line 34 like //#define config_h. Have a look at my grbl edge.

**Comment by EliteEng** [comment]
Thanks @abetusk @alpharesearch that has done the trick, just a lot of warnings of them being redefined. But it is all working

**Comment by EliteEng** [comment]
if you add

#ifndef DEFAULTS_GENERIC
  #define DEFAULTS_GENERIC
  #define CPU_MAP_ATMEGA328P_TRADITIONAL
#endif

to the sim/config.h it fixes the problem

**Pull request merged**
