### PR TITLE
fixed build errors on linux

### PR DESCRIPTION
**Pull request by flynneva**
- fixed some variable naming
- removed jog.o from make file (removed from grbl it looks like)

### CODE REVIEW

**Comment by flynneva** [comment]
fixes #23

**Comment by haoshuiwuxiang** [comment]
Hello, I found that this is caused by the grbl version. Replace the grbl source code to 1.1. It seems that the grbl variable referenced in SIM is the name in version 1.1.

**Comment by flynneva** [comment]
Oh ok that makes sense. Should I still keep this PR open though and bump the version number somewhere so people know which one it targets?

**Comment by haoshuiwuxiang** [comment]
> Oh ok that makes sense. Should I still keep this PR open though and bump the version number somewhere so people know which one it targets?

I think so. But I have another problem, I successfully compiled the SIM. How to use it to visualize the running process of grbl? I only saw the same serial palindrome interface as running on arduino. Do you have any suggestions?

**Comment by flynneva** [comment]
> How to use it to visualize the running process of grbl? I only saw the same serial palindrome interface as running on arduino. Do you have any suggestions?

once compiled there should be a `grbl_sim.exe` file to execute. you can run that directly to interact with a grbl virtual device or run the shell script provided `simport.sh` that runs it as a virtual device on the `/tmp/ttyFAKE` interface.  I updated that script also in my PR since there was a typo.

image

**Comment by flynneva** [comment]
to visualize it......i think any GRBL visualization software could be directed to use that `/tmp/ttyFAKE` interface and it should work.  I personally love using the [open builds control software](https://software.openbuilds.com/) and is what I use on my CNC.

i'm working a way to [connect GRBL to ROS2](https://github.com/flynneva/grbl_ros.git) though to allow for more robotics integration too down the road. still a work in progress but....hey ill share it just so you know about it.

**Comment by nickm324** [comment]
Just cloned the current version of grbl-sim, have the lastest version of grbl source 1.1h and I am still getting the make new error. 
What am I missing?

**Pull request closed without merging**
