### PR TITLE
Updated simport.sh to change the permission on /dev/ttyFAKE

### PR DESCRIPTION
**Pull request by winder**
I was having some trouble getting socat to work for me, so I updated the simport.sh script to change permission on /dev/ttyFAKE afterwards.

### CODE REVIEW

**Comment by ashelly** [comment]
Looks good. Let me verify it still works for me and then I'll pull.

**Comment by cheton** [comment]
I can confirm the PR works well in my Linux environment.

**Comment by winder** [comment]
This works fine on OSX as well.

**Comment by ashelly** [comment]
I have been busy with a new job. I will try to take a look tomorrow.

**Pull request closed without merging**
